import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Colors } from "@/styles/color";
import Bottombar from "@/components/Bottombar";

const wantedSans = localFont({
  src: "./fonts/WantedSansVariable.woff2",
  variable: "--font-wanted-sans",
  weight: "100 900",
  style: "normal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "✨ Journal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        style={{
          backgroundColor: Colors.primary_color,
          margin: 0,
        }}
        className={wantedSans.variable}
      >
        <Navbar />
        <Bottombar />
        {children}
      </body>
    </html>
  );
}
